version: '3'
services:
  python3:
    build: .
    working_dir: /root/
    container_name: python3.6
    tty: true
    volumes:
      - ./src:/root/workspace/src
      - ./config:/root/.config/matplotlib
    ports:
      - "8888:8888"